namespace CombatLogging.Entries
{
    public enum CombatLogEntryType
    {
        SKILL_USED,
        BATTLEGROUND_STATUS_EFFECT_CHANGED,
        REMOVE_STATUS_EFFECT,
        REMOVE_BATTLEGROUND_STATUS_EFFECT,
        TURN_CHANGED,
        ENTITY_DIED,
        BATTLE_FINISHED,
        ENTITY_CHANGED,
        ENTITY_DAMAGED,
        ENTITY_MAX_RESOURCE_CHANGED,
        ENTITY_MANA_CHANGED,
        ENTITY_STATUS_EFFECT_CHANGED,
        ENTITY_STAT_CHANGED
    }

}
