public enum CombatLogEntryType
{
    USE_ABILITY,
    HP_CHANGED,
    MANA_CHANGED,
    ADD_STATUS_EFFECT,
    REMOVE_STATUS_EFFECT,
    ADD_BATTLEGROUND_STATUS_EFFECT,
    REMOVE_BATTLEGROUND_STATUS_EFFECT,
    DIED,
    RECALLED,
    SUMMONED,
    RESULT,
    NEW_TURN
}
